version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
